# Reference: https://github.com/marketplace/actions/deploy-to-github-pages
name: Install and Build
on:
  pull_request:

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: | 
          echo "Verifying Install and Build"
          pwd
          ls

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: End
        run: echo "Complete"
