# Reference: https://github.com/marketplace/actions/deploy-to-github-pages
name: Install and Build
on:
  pull_request:

jobs:
  install-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo "Verifying Install and Build"
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
      - name: End
        run: echo "Complete"
